### ISSUE TITLE
[AWS Cloudformation] Join list of singular function or string for Resources/Node0/Properties/NetworkInterfaces/0/PrivateIpAddress/Fn::Join 

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-machine-image#212]
Join list of singular function or string for Resources/Node0/Properties/NetworkInterfaces/0/PrivateIpAddress/Fn::Join 

### For all nodes:
```
  Node0:
    Condition: Launch1
    Type: 'AWS::EC2::Instance'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    DependsOn: CfnEndpoint
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 50
      ImageId: !Ref ScyllaAmi
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Sub '${ScyllaClusterName}-Node-1'
        - Key: ScyllaClusterName
          Value: !Ref ScyllaClusterName
      UserData: !Base64
        'Fn::Join':
          - ''
          - - '{"scylla_yaml": {"seed_provider": [{"class_name": "org.apache.cassandra.locator.SimpleSeedProvider", "parameters": [{"seeds": "'
            - !Join
              - ','
              - - !If [Launch1, !Select [0, !Ref ScyllaSeedIPs], !Ref "AWS::NoValue"]
                - !If [Launch2, !Select [1, !Ref ScyllaSeedIPs], !Ref "AWS::NoValue"]
                - !If [Launch3, !Select [2, !Ref ScyllaSeedIPs], !Ref "AWS::NoValue"]
            - '"}]}]'
            - !Sub ', "cluster_name": "${ScyllaClusterName}", '
            - '"endpoint_snitch": "org.apache.cassandra.locator.Ec2Snitch"}, '
            - '"start_scylla_on_first_boot": true, '
            - '"post_configuration_script" : "'
            - !Base64
              'Fn::Join':
                - ''
                - - !Sub |
                    #!/bin/bash -ex
                    /usr/local/bin/cfn-signal --exit-code 0 --resource Node0 --region ${AWS::Region} --stack ${AWS::StackName}
            - '"}'
      NetworkInterfaces:
        - AssociatePublicIpAddress: !Ref EnablePublicAccess
          PrivateIpAddress: !Join
            - '.'
            - - !Select [0, !Split ['.', !Select [0, !Split ['/', !Ref CIDR]]]]
              - !Select [1, !Split ['.', !Select [0, !Split ['/', !Ref CIDR]]]]
              - !Select [2, !Split ['.', !Select [0, !Split ['/', !Ref CIDR]]]]
              - 10
          SubnetId: !Ref Subnet
          DeviceIndex: '0'
          Description: 'Primary network interface'
          GroupSet:
            - !Ref SGCluster
            - !Ref SGAdmin
```
