### ISSUE TITLE
[AWS Cloudformation] Security Groups ingress with an ipProtocol of -1 found.

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-machine-image#213]
Security Groups ingress with an ipProtocol of -1 found. Do you need all protocols (tcp, udp, icmp, or icmpv6)? 

```
  SGCluster:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for the cluster
      Tags:
        - Key: Name
          Value: !Sub '${ScyllaClusterName}-SGCluster'
        - Key: ScyllaClusterName
          Value: !Ref ScyllaClusterName
      SecurityGroupIngress:
        - CidrIp: !Ref CIDR
          IpProtocol: '-1'
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
      VpcId: !Ref VPC
```
