### ISSUE TITLE
Fail to use Scylla 4.0rc1 user data

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-machine-image#24]
I launch a new Scylla Cluster with 4.0rc1 AMIs, and fail to create a cluster

AMI: ScyllaDB 4.0.rc1 (ami-0ddd86daaba39d1d1) (us-east-1)

User data
```
{
     "scylla_yaml": {
         "cluster_name": "my-test-cluster",
         "experimental": true,
  }
}
```
Is the above valid?

Looking at one of the the instance configuration, it seems cluster name (and maybe more params) are not set correctly

> cat /etc/scylla/scylla.yaml

```
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: false
batch_size_fail_threshold_in_kb: 50
batch_size_warn_threshold_in_kb: 5
broadcast_rpc_address: 10.99.0.99
cas_contention_timeout_in_ms: 1000
cluster_name: scylladb-cluster-1586337017
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: org.apache.cassandra.locator.Ec2Snitch
experimental: false
listen_address: 10.99.0.99
murmur3_partitioner_ignore_msb_bits: 12
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 0.0.0.0
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 10.99.0.99
write_request_timeout_in_ms: 2000

```
