### ISSUE TITLE
minimalistic scylla.yaml on Scylla AMI

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-machine-image#26]
Scylla 4.0 AMI include (I assume) only small subset of the parameters
```
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
auto_bootstrap: false
batch_size_fail_threshold_in_kb: 50
batch_size_warn_threshold_in_kb: 5
broadcast_rpc_address: 172.31.34.160
cas_contention_timeout_in_ms: 1000
cluster_name: my-test-cluster
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
endpoint_snitch: org.apache.cassandra.locator.Ec2Snitch
experimental: true
listen_address: 172.31.34.160
murmur3_partitioner_ignore_msb_bits: 12
native_transport_port: 9042
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 0.0.0.0
rpc_port: 9160
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 172.31.34.160
write_request_timeout_in_ms: 2000
```

This is less useful than the full blow scylla.yaml, which includes many parameters as comments, as well as description per parameters.
This extra comments are very helpful when one need to update the yaml file.
